name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
       # Clean install to fix rollup module issue
      - run: rm -rf node_modules package-lock.json
      - run: npm install

      - run: npm run build --if-present
      - run: npm test